[build]
buildCommand = "pip install -r requirements.txt && python bot/create_samples.py"

[deploy]
startCommand = "python bot/bot.py"
restartPolicyType = "always"
healthcheckPath = "/"
healthcheckTimeout = 300
